# Generated by Django 5.0.6 on 2025-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('table_html', models.TextField(help_text='HTML-код таблицы')),
                ('chart_image', models.ImageField(upload_to='statistics/charts/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
