# Generated by Django 5.0.6 on 2025-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalstatistic',
            options={'ordering': ['name'], 'verbose_name': 'Блок статистики', 'verbose_name_plural': 'Общая статистика'},
        ),
        migrations.AlterField(
            model_name='generalstatistic',
            name='chart_image',
            field=models.ImageField(upload_to='statistics/charts/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='generalstatistic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='generalstatistic',
            name='name',
            field=models.SlugField(unique=True, verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='generalstatistic',
            name='table_html',
            field=models.TextField(verbose_name='HTML‑таблица'),
        ),
        migrations.AlterField(
            model_name='generalstatistic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
