# Generated by Django 5.0.6 on 2025-06-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_demandstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Системное имя (slug)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок блока')),
                ('table_html', models.TextField(verbose_name='HTML‑таблица')),
                ('chart_image', models.ImageField(upload_to='statistics/geography/', verbose_name='График')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блок географии',
                'verbose_name_plural': 'География',
                'ordering': ['name'],
            },
        ),
    ]
