# Generated by Django 5.0.6 on 2025-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HHVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки (через запятую)')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Оклад')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Валюта')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Ссылка на вакансию')),
            ],
            options={
                'verbose_name': 'Вакансия HH',
                'verbose_name_plural': 'Вакансии HH',
                'ordering': ['-published_at'],
            },
        ),
    ]
