# Generated by Django 5.0.6 on 2025-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Уникальный идентификатор страницы, например 'home'", unique=True)),
                ('title', models.CharField(help_text='Заголовок страницы, выводится в теге <h2>', max_length=100)),
                ('body', models.TextField(help_text='HTML‑контент страницы, можно вставлять <p>, <img> и т.д.')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контенты страниц',
            },
        ),
    ]
